Click "iPadBookmarks"

Click "NickMomPlayerTest"

(*Click "NickMomPlayerTest02"*)

(*Click "iPadRefresh"*)

(*MoveTo "iPadPosterPlay"*)
(*MoveTo "iPadPlay"*)

waitfor 60, "iPadPosterPlay"
Click "iPadPosterPlay"

(*if ImageFound("iPadAdContent") 
	moveto FoundImageLocation()
	wait 35
end if*)

waitfor 30, "IPadPause"
Click "IPadPause"

drag "iPadSlider"
drop "iPadEndPoint2"

wait 5

if ImageFound("iPadPlay") 
	click FoundImageLocation()
end if

waitfor 120, "iPadReplay"
moveto "iPadReplay"
